/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prueba.h"
#include <string.h>

void calculadora_prog_1(char *host, enum operation *operation, int number1, int number2);

void calculadora_prog_1(char *host, enum operation *operation, int number1, int number2)
{
	CLIENT *client;
	operandos numbers;
	int *result;

#ifndef	DEBUG
	client = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (client == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (operation) {
		case 0:
			result = suma_1(&number2, client);
			if(result == NULL) {
				clnt_perror (client, "call failed");
			}
			break;
		case 1:

			break;
		case 2:

			break;
		case 3:

			break;
		default:

			break;
	}


#ifndef	DEBUG
	clnt_destroy(client);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	enum operation {
		suma = 0,
		resta = 1,
		multiplicacion = 2,
		division = 3
	};

	char *host;
	enum operation operation;
	int number1;
	int number2;

	if (argc != 4) {
		printf ("usage: %s <server_host> <SUMA|MULTIPLICACION> <NUMBER1> <NUMBER2>\n", argv[0]);
		exit (1);
	}
	
	if(strcmp(argv[2], "SUMA") == 0) {
		operation = suma;
	}
	else if(strcmp(argv[2], "RESTA") == 0) {
		operation = resta;
	}
	else if(strcmp(argv[2], "MULTIPICACION") == 0) {
		operation = multiplicacion;
	}
	else if(strcmp(argv[2], "DIVISION") == 0) {
		operation = division;
	}
	host = argv[1];
	number1 = atoi(argv[3]);
	number1 = atoi(argv[3]);
	calculadora_prog_1(host, &operation, number1, number2);
	
	exit(0);
}
