/*------------------------------------------------------------------------------
Practice 1 Exercise 2
guess.cc
This program asks for a number to the user and generates a random number between
1 and 10. The program says to the user if the number he has introduced is 
greater, less or equal to the number generated by the program.
------------------------------------------------------------------------------*/

#include <iostream>
#include <cstdlib>
#include <ctime>

int main () {

    int user_number;
    int program_number;

    std::cout << "Introduce a number from 1 to 10 ";
    std::cin >> user_number;
    //Check if the number introduced by the user is between 1 and 10
    if (user_number < 1 || user_number > 10) {
      std::cout << ("The number has to be between 1 and 10: ");
      std::cin >> user_number;
    }

    //Generating a random number between 1 and 10
    srand(time(NULL));
    program_number = (rand() % 11) + 1;

    if (user_number < program_number) {
      std::cout << "Your number is greater than the one generated (" << program_number << ")\n";
    }
    if (user_number > program_number) {
      std::cout << "Your number is less than the one generated (" << program_number << ")\n";
    }
    if (user_number == program_number) {
      std::cout << "Your number is equal to the one generated (" << program_number << ")\n";
    }

  return 0;
}
