todo: crea visualiza

#Construye el ejecuatable para crear un fichero binario a partir de uno de texto
crea: creaBinario.c
	gcc -o crea creaBinario.c
	
#Construye el ejecuatable para visualizar un fichero binario
visualiza: visualiza.c
	gcc -o visualiza visualiza.c
